# Generated by Django 5.2 on 2025-04-15 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=8)),
                ('filmmaker', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='movies_images/')),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
