# Generated by Django 5.2 on 2025-04-30 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
