# Generated by Django 5.2 on 2025-07-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
    ]
