# Generated by Django 5.2 on 2025-04-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_remove_showtimes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
