# Generated by Django 5.2 on 2025-04-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinemas', verbose_name='Кинотеатр')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Фильм')),
            ],
            options={
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
