# Generated by Django 5.2 on 2025-04-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtimes',
            options={'verbose_name_plural': 'Showtimes'},
        ),
    ]
