# Generated by Django 5.2 on 2025-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0004_showtimes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='status',
            field=models.BooleanField(verbose_name='Прошел ли?'),
        ),
    ]
