# Generated by Django 5.2 on 2025-04-15 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cinema_images/', verbose_name='Изображение кинотеатра')),
            ],
            options={
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер зала')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='cinemas.cinemas', verbose_name='Кинотеатр')),
            ],
            options={
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
