# Generated by Django 5.2 on 2025-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_cinemas_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='coordinates',
            field=models.JSONField(default=[0, 0]),
        ),
    ]
