# Generated by Django 5.2 on 2025-04-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_alter_cinemas_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name_plural': 'Cinemas'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name_plural': 'Halls'},
        ),
    ]
