# Generated by Django 5.2 on 2025-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_alter_cinemas_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
