# Generated by Django 5.2 on 2025-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Чат ID'),
        ),
    ]
