# Generated by Django 5.2 on 2025-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_token_alter_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Чат ID'),
        ),
    ]
