# Generated by Django 5.2 on 2025-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(),
        ),
    ]
