# Generated by Django 5.2 on 2025-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movies_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movies',
            name='year_published',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
