# Generated by Django 5.2 on 2025-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_orders_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qr',
            field=models.ImageField(blank=True, upload_to='orders_qr/', verbose_name='QR код'),
        ),
    ]
