# Generated by Django 5.2 on 2025-07-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customuser',
            new_name='user',
        ),
    ]
